### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by bckohan** [jazzband/django-polymorphic#599]
Getting deprecation warnings in my projects that use django-polymorphic

I will submit a PR.

**Comment by bckohan** [comment]
Ah, I see this was already fixed in master.

**Comment by martin-thoma** [comment]
Why wasn't there a release for django-polymorphic for such a long time? 
https://pypi.org/project/django-polymorphic/

**Comment by jedie** [comment]
This is still not released?!? So Python 3.12 installation are broken by:
```
...
   File "/home/runner/work/bx_django_utils/bx_django_utils/bx_django_utils_tests/test_app/models.py", line 5, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/runner/work/bx_django_utils/bx_django_utils/.tox/py312-django50/lib/python3.12/site-packages/polymorphic/__init__.py", line 9, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by martin-thoma** [comment]
You can install from github. I guess at the moment that is the only option.
